src/report_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .veiws import login_veiw,logout_veiw

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("sales.urls",namespace="sales")),
    path("reports/", include("reports.urls", namespace="reports")),
    path("profiles/", include("profiles.urls", namespace="profiles")),
    path("login/",login_veiw,name="login"),
    path("logout/",logout_veiw,name="logout")
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/reports/urls.py
from django.urls import path
from .views import (
    create_report_veiw,
    ReportListView,
    ReportDetailView,
    render_pdf_view,
    )

app_name = "reports"

urlpatterns = [
    path("",ReportListView.as_view(),name="main"),
    path("save/", create_report_veiw, name="create-report"),
    path("<pk>/", ReportDetailView.as_view(),name="detail"),
    path("<pk>/pdf/", render_pdf_view, name="pdf"),
]

src/sales/urls.py
from django.urls import path
from .views import home_view, SaleListView, SaleDetailView, UploadTemplateView, csv_upload

app_name = "sales"

urlpatterns = [
    path('', home_view, name="home"),
    path("sales/", SaleListView.as_view(), name="list"),
    path("upload/", UploadTemplateView.as_view(), name="upload"),
    path("from_file/", csv_upload, name="from-file"),
    path("sales/<pk>/", SaleDetailView.as_view(), name="detail"),
]

src/reports/models.py
from django.db import models
from profiles.models import Profile
from django.urls import reverse
# Create your models here.

class Report(models.Model):
    name = models.CharField(max_length=120)
    image = models.ImageField(upload_to="reports",blank=True)
    remarks = models.TextField()
    author = models.ForeignKey(Profile,on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse ( "reports:detail", kwargs={"pk" : self.pk} )
    def __str__(self):
        return str(self.name)


    class Meta:
        ordering = ('-created',)

src/reports/forms.py
from django import forms
from .models import Report

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('name','remarks')

src/reports/views.py
from django.shortcuts import render,get_object_or_404
from profiles.models import Profile
from django.http import JsonResponse
from .utlis import get_report_image
from .models import Report
from django.views.generic import ListView,DetailView

from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
#o Create your views here.

class ReportListView(LoginRequiredMixin,ListView):
    model = Report
    template_name = "reports/main.html"


class ReportDetailView(LoginRequiredMixin, DetailView):
    model = Report
    template_name = "reports/detail.html"


@login_required
def create_report_veiw(request):
    if request.is_ajax:
        name = request.POST.get('name')
        remarks = request.POST.get('remarks')
        image = request.POST.get("image") 
        author = Profile.objects.get(user=request.user )
        img = get_report_image(image)
        Report.objects.create(name=name, remarks=remarks, image=img,author=author,)
        return JsonResponse({'msg':"send"})
    return JsonResponse({})

@login_required
def render_pdf_view(request,pk):
    template_path = 'reports/pdf.html'
    obj = get_object_or_404(Report,pk=pk)
    context = {'obj': obj}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # if download
    # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # if display
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
        html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

src/reports/templates/reports/detail.html
{% extends "base.html" %}

{% block title %}
{{ object.name }}
{% endblock title %}

{% block content %}
    {% if object.image %}
        <img src="{{ object.image.url }}" class="img-fluid" alt="{{ object.name }}">
    {% endif %}
    <br>
    <h3>Remarks</h3>
    <p>{{ object.remarks }}</p>
    <hr>
    <p>author: <b>{{ object.author.user.username }}</b></p>
    <p>created: <b>{{ object.created }}</b></p>
{% endblock content %}

src/reports/templates/reports/main.html
{% extends "base.html" %}

{% block title %}
reports
{% endblock title %}

{% block content %}
<h4>reports</h4><br>
{% for obj in object_list %}
    <div class="card mb-3" >
        {% if obj.image %}
            <img src="{{obj.image.url}}" class="card-img-top" alt="{{ obj.name }}">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ obj.name }}</h5>
            <p class="card-text">{{ obj.remarks|truncatewords:2 }}</p>
            <a href="{{obj.get_absolute_url}}" class="btn btn-primary">details</a>
            <a href="{% url 'reports:pdf' obj.pk %}" class="btn btn-danger">pdf</a>
        </div>
    </div>



{% endfor %}
{% endblock content %}


<!-- style="width: 18rem;" -->

src/reports/templates/reports/pdf.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">

    <title>PDF {{obj.name}}</title>
    <style>
        .image{
            width: 100%;
            height : auto;
        }
    </style>
</head>

<body>
<h1>{{ obj.name }}</h1>
<hr>
<img src="{{ obj.image.path }}" class="imaqge">
<br>
<h3> Remarks </h3>
<p>{{ obj.remarks }}</p>
<hr>
<p>author: <b>{{ obj.author.user.username }}</b></p>
<p>created: <b>{{ obj.created }}</b></p>
</body>

</html>